아이템 닿았을 때 효과음 추가
ItemText2/3 적용
집사/고양이 텍스트 전환 및 효과음 재생 기능 추가
개별 스테이지에서는 정상작동하나 다음 스테이지로 넘어가는 경우 2개의 null reference 오류가 발생함
씬 전환과 동시에 꺼지는 경우: NullReferenceException: Object reference not set to an instance of an object
CatControlAndSound.OnCollisionEnter2D (UnityEngine.Collision2D collision) (at Assets/Scripts/Chapter1/CatControlAndSound.cs:83)
씬 전환 후 아이템에 닿았을 때 꺼지는 경우:
NullReferenceException: Object reference not set to an instance of an object
ItemText3.OnTriggerEnter2D (UnityEngine.Collider2D collision) (at Assets/Scripts/Chapter3/ItemText3.cs:32)